# This is a basic workflow to help you get started with Actions

name: douglas

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: '1.0.0' - removido
          terraform_wrapper: false # adicionado

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        # run: terraform apply -auto-approve -var="create_key=true" - alterado
        run: terraform apply -auto-approve

      - name: Set INSTANCE_IP environment variable # adicionado
        run: echo "instance_ip=`terraform output -raw instance_ip`" >> $GITHUB_ENV # adicionado

      - name: Wait for instance to be ready
        run: sleep 60  # waits for 60 seconds

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Create Ansible Inventory
        run: |
          echo "[douglas_vm]" > inventory.ini
          echo "${instance_ip}" >> inventory.ini
          echo "" >> inventory.ini
          cat inventory.ini
          
      - name: host key # adicionado
        run: ssh-keyscan ${instance_ip} >> ~/.ssh/known_hosts # adicionado

      - name: Run Ansible Playbook
        # run: ansible-playbook -i inventory.ini playbook.yml - alterado
        run: ansible-playbook -i inventory.ini ansible-playbook-install-docker.yml
